LIST p=16f628a
INCLUDE <p16f628a.inc>
	
	NUM 	EQU 20H
	TEC 	EQU 21H
	VAR1 	EQU 22H
	VAR2 	EQU 23H
	VAR3 	EQU 24H
	VAR4 	EQU 25H
	VAR5	EQU 26H
	VAR6	EQU 27H
	SUMA 	EQU 28H

	NUM.1 equ b'11101100'  
	NUM.2 equ b'10000000'
	NUM.3 equ b'10001000'
	NUM.4 equ b'10001100'
	NUM.5 equ b'10001001'
	NUM.6 equ b'10000001'
	NUM.7 equ b'11101100'
	NUM.8 equ b'10100010'
	NUM.9 equ b'10101000'
	LET.A equ b'10000100' 
	NUM.0 equ b'11000000'
	LET.b equ b'10000001'

	ORG 	0x00
	GOTO	INICIO
	ORG		0x04
	GOTO	INTERRUPCION	

	
INICIO 

	MOVLW 	0x07 
 	BSF 	STATUS,RP0 
	CLRF 	TRISA 
	BSF 	TRISA,5
 	MOVLW 	b'11100001' 
 	MOVWF 	TRISB 
 	BCF 	OPTION_REG,NOT_RBPU							; habilitadas
 	BCF 	STATUS,RP0 
 
	BSF 	INTCON,GIE
	BSF 	INTCON,INTE 
	BSF 	STATUS,RP0
	BCF 	OPTION_REG,INTEDG
	BCF 	STATUS,RP0
	CLRF  	SUMA

PRINCIPAL

	CALL	 TECLADO
 	MOVWF 	 VAR1 
 	CALL 	 TECLADO
 	MOVWF 	 VAR2
 	CALL 	 TECLADO
 	MOVWF 	 VAR3
	CALL	 TECLADO
 	MOVWF	 VAR4
	CALL	 TECLADO
 	MOVWF	 VAR5
	CALL	 TECLADO
 	MOVWF	 VAR6
 	
COND1   MOVLW	NUM.0
		SUBWF	VAR1,0
		BTFSC	STATUS,Z
		GOTO	COND2
		GOTO    INCORRECTO	

COND2 	MOVLW	NUM.2
		SUBWF	VAR2,0
		BTFSC	STATUS,Z
		GOTO	COND3
		GOTO    INCORRECTO

COND3   MOVLW	NUM.0
		SUBWF	VAR3,0
		BTFSC	STATUS,Z
		GOTO	COND4
		GOTO    INCORRECTO


COND4 	MOVLW	NUM.8
		SUBWF	VAR4,0
		BTFSC	STATUS,Z
		GOTO	COND5
		GOTO    INCORRECTO

COND5 	MOVLW	NUM.9
		SUBWF	VAR5,0
		BTFSC	STATUS,Z
		GOTO	COND6
		GOTO    INCORRECTO

COND6 	MOVLW	NUM.7
		SUBWF	VAR6,0
		BTFSC	STATUS,Z
		GOTO	CORRECTO
		GOTO    INCORRECTO

	    	    
INCORRECTO 
			
		BTFSC 	PORTB,0
		GOTO 	$-1
		BSF 	PORTA,6
		GOTO 	PRINCIPAL
			
CORRECTO   
			
		BTFSC 	PORTB,0
		GOTO	$-1
		BCF 	PORTA,6
		BSF 	PORTA,4
		CLRF 	PORTA					
		CLRF  	SUMA
		BSF  	INTCON,GIE
		BSF  	INTCON,INTE
		GOTO 	PRINCIPAL
			
INTERRUPCION
		
		BCF   	INTCON,1
		INCF  	SUMA,1
		MOVLW	B'00111111'
		ANDWF 	SUMA
		MOVF  	SUMA,0
		MOVWF 	PORTA
		BSF 	PORTA,6
								
		SUBLW 	D'3'
		BTFSS 	STATUS,Z	
		RETFIE 		
		BSF   	PORTA,7
		BCF   	INTCON,GIE
		BCF   	INTCON,INTE
		RETFIE


TECLADO 

	CLRF 	TEC
 	MOVLW 	b'00001101' 
 	MOVWF 	PORTB 

REVISARCOLUMNA

 	BTFSS 	PORTB,5 
 	GOTO	ANTIRREBOTES 
 	INCF 	TEC,f 
 	BTFSS 	PORTB,6 
 	GOTO 	ANTIRREBOTES 
 	INCF 	TEC,f 
 	BTFSS 	PORTB,7 
 	GOTO 	ANTIRREBOTES 
 	INCF 	TEC,f 

	MOVLW 	d'12'
 	SUBWF 	TEC,w
 	BTFSC 	STATUS,Z
 	GOTO 	TECLADO
	BSF 	STATUS,C
 	RLF 	PORTB,f
 	GOTO 	REVISARCOLUMNA

ANTIRREBOTES
	B1 BTFSS PORTB,5
 	   GOTO B1
	B2 BTFSS PORTB,6
       GOTO B2
	B3 BTFSS PORTB,7
       GOTO B3

 	   MOVF TEC,w
       CALL REVISARTECLA
       RETURN

REVISARTECLA
   	   ADDWF PCL,f
	   RETLW NUM.1
 	   RETLW NUM.2
 	   RETLW NUM.3
 	   RETLW NUM.4
 	   RETLW NUM.5
 	   RETLW NUM.6
 	   RETLW NUM.7
 	   RETLW NUM.8
 	   RETLW NUM.9
 	   RETLW LET.A
 	   RETLW NUM.0
 	   RETLW LET.b

END
